# fly.toml file generated for redwood-docker on 2021-09-08T13:19:29+02:00

app = "redwood-docker"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[env]
  API_PROXY_PATH = "https://redwood-docker.fly.dev/api/graphql"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8911
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
